spring:
    application:
        name: apigateway
#    cloud:
#        gateway:
##            default-filters:
##                -   name: AuthFilter
##                    args:
##                        regex: /(?<path>.*)
##                        replacement: /auth-service/v1/$\{path}
#            routes:
#                - id: auth
#                  uri: localhost:8081
#                  predicates:
#                    - Path=/api/v1/auth/**
#                - id: test
#                  uri: localhost:8086
#                  predicates:
#                    - Path=/test/**


server:
    port: 9000

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
#        fetch-registry: true
#        register-with-eureka: true

logging:
    level:
        root: INFO


