spring:
    application:
        name: auth
    #  datasource:
    #    url: jdbc:postgresql://ep-steep-mode-85453895-pooler.ap-southeast-1.postgres.vercel-storage.com:5432/verceldb
    #    username: default
    #    password: BYQyt1SX0fcp
    #    driver-class-name: org.postgresql.Driver
    #  ----- MySQL -----
    datasource:
        url: jdbc:mysql://localhost:3306/your_database_name?createDatabaseIfNotExist=true
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
    #------------
    jpa:
        hibernate:
            ddl-auto: update
        #    show-sql: true
        properties:
            hibernate:
                format_sql: true
#        ------------
#        dialect: org.hibernate.dialect.MySQL5Dialect
#        ------------
#    database: postgresql
#    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8081

application:
    security:
        jwt:
            secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
            expiration: 86400000 # a day
            refresh-token:
                expiration: 604800000 # 7 days

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true

